IMAGE_NAME = huyurt/s2i-dotnet-libgdiplus-runtime:7.0

# Create an Image Builder named above based on the Dockerfile that was created previously.
.PHONY: build
build:
	docker build -t $(IMAGE_NAME) .
